name: build docker image and push to docker hub

on:
  push:
    branches:
      - main
jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      app_work_directory: ./application
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: build docker image and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./application
          tags: maziar110/web-monitor-consumer:latest


