name: build docker image and push to docker hub

on:
  push:
    branches:
      - main
      - test-action
jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      app_work_directory: ./web_monitor_consumer/applications
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: Change of directory
        run: cd $app_work_directory
      - name: build docker image and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: maziar110/web-monitor-consumer:latest


